### ISSUE TITLE
Replace image with Ruby:2.7+

### ISSUE THREAD

**Issue by ckenst** [TestingConferences/testingconferences.github.io#631]
GitHub doesn't allow going beyond Jekyll 3.9. Other dependencies (like `activesupport`) need later versions of Ruby such as 2.7. For this reason we need to create our own image or rebuild our docker-compose file to allow the use a generic ruby image and then mount and install the jekyll dependencies. 

```
version: "2"
services:
  testingconferences:
    image: jekyll/jekyll:3.8.6
    container_name: tcorg
    ports:
      - 4000:4000 # jekyll ui
    command: sh -c "bundle install && jekyll serve"
    restart: unless-stopped
    platform: linux/amd64
    volumes:
      - ./:/srv/jekyll
```
